# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da1808f4fc8991dab8d2201e6063621f9ebf191b19e8cb144f1aee25384cc199772a232897ed10c3e4aa6fdb6137b26824a5c32b7de136ca822c02f77ac7441c

test:
  secret_key_base: a4521a1461f971f72c3fe8d90a06029cf5043aa780de919433c990911028cce3cdad2e2be851ff6e51d0ed1898056b6f2ed2b237362b13fe1f52ea52af65f017

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
